server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:wf-gateway}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: ${GATEWAY_DISCOVERY_LOCATOR_ENABLED:true}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_URL:http://localhost:8761/eureka}